name: llama
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: pixel <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  worker2: any
  resource: any
  path: any
#  path: ^1.4.1

dev_dependencies:
  test: any
